<a href="https://colab.research.google.com/github/reedburmaster/mis433/blob/main/DataManipulationAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation in Pandas

In this assignment, you will be working on the same dataframe of flights departing New York City in 2013.

In [1]:
import pandas as pd

In [6]:
# Install the package 'nycflights13' before you can run this
!pip install nycflights13
from nycflights13 import flights
flights.head()

Collecting nycflights13
  Downloading nycflights13-0.0.3.tar.gz (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 62.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)
Building wheels for collected packages: nycflights13
  Building wheel for nycflights13 (setup.py) ... done
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732722 sha256=d63931916b388625784b297c322608ca96ccd2739eb2473fc1b2f914f0e4224e
  Stored in directory: /root/.cache/pip/wheels/58/ee/20/7838832df5510701439239ec10c2d8927de32aac2729ce2085
Successfully built nycflights13
Installing collected packages: nycflights13
Successfully installed nycflights13-0.0.3

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [7]:
flights.shape

(336776, 19)

## Data frame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [8]:
# use describe() to summarize all columns
flights.describe(include='all')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,336776.000000,334264,336776,336776,327346.000000,336776.000000,336776.000000,336776.000000,336776
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,4043,3,105,NaN,NaN,NaN,NaN,6936
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,NaN,N725MQ,EWR,ORD,NaN,NaN,NaN,NaN,2013-09-13T12:00:00Z
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,NaN,575,120835,17283,NaN,NaN,NaN,NaN,94
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,1971.923620,NaN,NaN,NaN,150.686460,1039.912604,13.180247,26.230100,NaN
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,1632.471938,NaN,NaN,NaN,93.688305,733.233033,4.661316,19.300846,NaN
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,1.000000,NaN,NaN,NaN,20.000000,17.000000,1.000000,0.000000,NaN
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,553.000000,NaN,NaN,NaN,82.000000,502.000000,9.000000,8.000000,NaN
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,1496.000000,NaN,NaN,NaN,129.000000,872.000000,13.000000,29.000000,NaN
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,3465.000000,NaN,NaN,NaN,192.000000,1389.000000,17.000000,44.000000,NaN
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,8500.000000,NaN,NaN,NaN,695.000000,4983.000000,23.000000,59.000000,NaN

## Question 1. Selecting rows

From the 'flights' dataframe, find all flights that satisfy the following certain conditions:

In [9]:
# Had an arrival delay of two or more hours
flights[flights['arr_delay'] >= 120]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
119,2013,1,1,811.0,630,101.0,1047.0,830,137.0,MQ,4576,N531MQ,LGA,CLT,118.0,544,6,30,2013-01-01T11:00:00Z
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
447,2013,1,1,1505.0,1310,115.0,1638.0,1431,127.0,EV,4497,N17984,EWR,RIC,63.0,277,13,10,2013-01-01T18:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,4294,N13988,EWR,SAV,95.0,708,16,49,2013-09-30T20:00:00Z
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,5292,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30T22:00:00Z
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T22:00:00Z
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z

In [10]:
# Flew to Houston (IAH or HOU)
flights[flights['dest'].isin(['IAH', 'HOU'])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
32,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,496,N459UA,LGA,IAH,229.0,1416,6,27,2013-01-01T11:00:00Z
81,2013,1,1,728.0,732,-4.0,1041.0,1038,3.0,UA,473,N488UA,LGA,IAH,238.0,1416,7,32,2013-01-01T12:00:00Z
89,2013,1,1,739.0,739,0.0,1104.0,1038,26.0,UA,1479,N37408,EWR,IAH,249.0,1400,7,39,2013-01-01T12:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336524,2013,9,30,1729.0,1720,9.0,2001.0,2010,-9.0,UA,652,N455UA,EWR,IAH,173.0,1400,17,20,2013-09-30T21:00:00Z
336527,2013,9,30,1735.0,1715,20.0,2010.0,2005,5.0,WN,2067,N296WN,EWR,HOU,188.0,1411,17,15,2013-09-30T21:00:00Z
336618,2013,9,30,1859.0,1859,0.0,2134.0,2159,-25.0,UA,1128,N14731,LGA,IAH,180.0,1416,18,59,2013-09-30T22:00:00Z
336694,2013,9,30,2015.0,2015,0.0,2244.0,2307,-23.0,UA,1545,N17730,EWR,IAH,174.0,1400,20,15,2013-10-01T00:00:00Z
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z

In [11]:
# Were operated by United (UA), American (AA), or Delta (DL)
flights[flights['carrier'].isin(['UA', 'AA', 'DL'])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01T10:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,2363,N193DN,JFK,LAX,296.0,2475,21,0,2013-10-01T01:00:00Z
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-10-01T01:00:00Z
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-10-01T01:00:00Z
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z

In [12]:
# Departed in July, August, and September
flights[flights['month'].isin([7, 8, 9])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
250450,2013,7,1,1.0,2029,212.0,236.0,2359,157.0,B6,915,N653JB,JFK,SFO,315.0,2586,20,29,2013-07-02T00:00:00Z
250451,2013,7,1,2.0,2359,3.0,344.0,344,0.0,B6,1503,N805JB,JFK,SJU,200.0,1598,23,59,2013-07-02T03:00:00Z
250452,2013,7,1,29.0,2245,104.0,151.0,1,110.0,B6,234,N348JB,JFK,BTV,66.0,266,22,45,2013-07-02T02:00:00Z
250453,2013,7,1,43.0,2130,193.0,322.0,14,188.0,B6,1371,N794JB,LGA,FLL,143.0,1076,21,30,2013-07-02T01:00:00Z
250454,2013,7,1,44.0,2150,174.0,300.0,100,120.0,AA,185,N324AA,JFK,LAX,297.0,2475,21,50,2013-07-02T01:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

In [13]:
# Arrived more than two hours late, but didn’t leave late
flights[(flights['arr_delay'] > 120) & (flights['dep_delay'] <= 0)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
22911,2013,1,27,1419.0,1420,-1.0,1754.0,1550,124.0,MQ,3728,N1EAMQ,EWR,ORD,135.0,719,14,20,2013-01-27T19:00:00Z
33011,2013,10,7,1350.0,1350,0.0,1736.0,1526,130.0,EV,5181,N611QX,LGA,MSN,117.0,812,13,50,2013-10-07T17:00:00Z
33019,2013,10,7,1357.0,1359,-2.0,1858.0,1654,124.0,AA,1151,N3CMAA,LGA,DFW,192.0,1389,13,59,2013-10-07T17:00:00Z
41075,2013,10,16,657.0,700,-3.0,1258.0,1056,122.0,B6,3,N703JB,JFK,SJU,225.0,1598,7,0,2013-10-16T11:00:00Z
55985,2013,11,1,658.0,700,-2.0,1329.0,1015,194.0,VX,399,N629VA,JFK,LAX,336.0,2475,7,0,2013-11-01T11:00:00Z
152766,2013,3,18,1844.0,1847,-3.0,39.0,2219,140.0,UA,389,N560UA,JFK,SFO,386.0,2586,18,47,2013-03-18T22:00:00Z
180893,2013,4,17,1635.0,1640,-5.0,2049.0,1845,124.0,MQ,4540,N721MQ,LGA,DTW,130.0,502,16,40,2013-04-17T20:00:00Z
181270,2013,4,18,558.0,600,-2.0,1149.0,850,179.0,AA,707,N3EXAA,LGA,DFW,234.0,1389,6,0,2013-04-18T10:00:00Z
181327,2013,4,18,655.0,700,-5.0,1213.0,950,143.0,AA,2083,N565AA,EWR,DFW,230.0,1372,7,0,2013-04-18T11:00:00Z
213693,2013,5,22,1827.0,1830,-3.0,2217.0,2010,127.0,MQ,4674,N518MQ,LGA,CLE,90.0,419,18,30,2013-05-22T22:00:00Z
214512,2013,5,23,1810.0,1810,0.0,2208.0,2000,128.0,MQ,4626,N525MQ,LGA,CMH,82.0,479,18,10,2013-05-23T22:00:00Z
226434,2013,6,5,1604.0,1615,-11.0,2041.0,1840,121.0,MQ,4657,N510MQ,LGA,ATL,158.0,762,16,15,2013-06-05T20:00:00Z
235033,2013,6,14,1708.0,1710,-2.0,2227.0,2015,132.0,AA,181,N320AA,JFK,LAX,334.0,2475,17,10,2013-06-14T21:00:00Z
244329,2013,6,24,1602.0,1605,-3.0,2134.0,1916,138.0,DL,706,N3768,JFK,AUS,247.0,1521,16,5,2013-06-24T20:00:00Z
247568,2013,6,27,2052.0,2100,-8.0,13.0,2210,123.0,US,2144,N952UW,LGA,BOS,46.0,184,21,0,2013-06-28T01:00:00Z
249957,2013,6,30,1423.0,1425,-2.0,1816.0,1554,142.0,B6,2402,N206JB,JFK,BUF,80.0,301,14,25,2013-06-30T18:00:00Z
250689,2013,7,1,905.0,905,0.0,1443.0,1223,140.0,DL,1057,N337NB,LGA,MIA,183.0,1096,9,5,2013-07-01T13:00:00Z
256340,2013,7,7,1659.0,1700,-1.0,2050.0,1823,147.0,US,2183,N948UW,LGA,DCA,64.0,214,17,0,2013-07-07T21:00:00Z
256358,2013,7,7,1727.0,1730,-3.0,2203.0,1951,132.0,F9,837,N263AV,LGA,DEN,236.0,1620,17,30,2013-07-07T21:00:00Z
256373,2013,7,7,1746.0,1755,-9.0,2133.0,1921,132.0,B6,1407,N374JB,JFK,IAD,78.0,228,17,55,2013-07-07T21:00:00Z
256405,2013,7,7,1823.0,1830,-7.0,2201.0,1955,126.0,MQ,3486,N724MQ,LGA,BNA,113.0,764,18,30,2013-07-07T22:00:00Z
270742,2013,7,22,1555.0,1600,-5.0,2139.0,1938,121.0,DL,141,N713TW,JFK,SFO,371.0,2586,16,0,2013-07-22T20:00:00Z
270752,2013,7,22,1606.0,1615,-9.0,2056.0,1831,145.0,DL,1619,N970DL,LGA,MSP,140.0,1020,16,15,2013-07-22T20:00:00Z
270762,2013,7,22,1628.0,1630,-2.0,2151.0,1939,132.0,B6,423,N625JB,JFK,LAX,332.0,2475,16,30,2013-07-22T20:00:00Z
276564,2013,7,28,1710.0,1711,-1.0,2248.0,2039,129.0,B6,167,N510JB,JFK,OAK,353.0,2576,17,11,2013-07-28T21:00:00Z
287148,2013,8,8,1457.0,1500,-3.0,1828.0,1624,124.0,US,2185,N746UW,LGA,DCA,70.0,214,15,0,2013-08-08T19:00:00Z
291439,2013,8,13,657.0,659,-2.0,1015.0,814,121.0,EV,4522,N14188,EWR,BNA,146.0,748,6,59,2013-08-13T10:00:00Z
305985,2013,8,28,1157.0,1200,-3.0,1520.0,1316,124.0,US,2179,N737US,LGA,DCA,63.0,214,12,0,2013-08-28T16:00:00Z
325764,2013,9,19,656.0,700,-4.0,1037.0,833,124.0,UA,331,N808UA,LGA,ORD,192.0,733,7,0,2013-09-19T11:00:00Z

In [14]:
# Were delayed by at least an hour, but made up over 30 minutes in flight
flights[(flights['dep_delay'] >= 60) & (flights['dep_delay'] - flights['arr_delay'] > 30)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
815,2013,1,1,2205.0,1720,285.0,46.0,2040,246.0,AA,1999,N5DNAA,EWR,MIA,146.0,1085,17,20,2013-01-01T22:00:00Z
832,2013,1,1,2326.0,2130,116.0,131.0,18,73.0,B6,199,N594JB,JFK,LAS,290.0,2248,21,30,2013-01-02T02:00:00Z
2286,2013,1,3,1503.0,1221,162.0,1803.0,1555,128.0,UA,551,N835UA,EWR,SFO,320.0,2565,12,21,2013-01-03T17:00:00Z
2508,2013,1,3,1839.0,1700,99.0,2056.0,1950,66.0,AA,575,N631AA,JFK,EGE,239.0,1747,17,0,2013-01-03T22:00:00Z
2522,2013,1,3,1850.0,1745,65.0,2148.0,2120,28.0,AA,177,N332AA,JFK,SFO,314.0,2586,17,45,2013-01-03T22:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336572,2013,9,30,1818.0,1715,63.0,2001.0,1940,21.0,9E,3310,N934XJ,JFK,MCI,142.0,1113,17,15,2013-09-30T21:00:00Z
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z
336674,2013,9,30,1956.0,1825,91.0,2208.0,2121,47.0,DL,1576,N3772H,JFK,SAN,292.0,2446,18,25,2013-09-30T22:00:00Z
336704,2013,9,30,2028.0,1910,78.0,2255.0,2215,40.0,AA,21,N338AA,JFK,LAX,294.0,2475,19,10,2013-09-30T23:00:00Z
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z

In [15]:
# Departed between midnight and 6am (inclusive)
flights[(flights['hour'] >= 0) & (flights['hour'] <= 6)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335886,2013,9,30,712.0,655,17.0,831.0,824,7.0,9E,3496,N909XJ,LGA,PIT,54.0,335,6,55,2013-09-30T10:00:00Z
335896,2013,9,30,724.0,600,84.0,946.0,840,66.0,B6,27,N558JB,EWR,MCO,126.0,937,6,0,2013-09-30T10:00:00Z
335905,2013,9,30,734.0,652,42.0,1001.0,954,7.0,UA,1439,N68452,EWR,LAX,297.0,2454,6,52,2013-09-30T10:00:00Z
335986,2013,9,30,827.0,615,132.0,1022.0,811,131.0,US,1772,N556UW,JFK,CLT,91.0,541,6,15,2013-09-30T10:00:00Z
336027,2013,9,30,858.0,659,119.0,1139.0,955,104.0,UA,537,N421UA,EWR,PBI,130.0,1023,6,59,2013-09-30T10:00:00Z

In [16]:
# How many flights have a missing dep_time?
flights['dep_time'].isna().sum()

np.int64(8255)

## Question 2. Sorting

In [17]:
# Sort flights to find the least delayed flights. Find the flights that left earliest.
flights.sort_values(by='dep_delay')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
89673,2013,12,7,2040.0,2123,-43.0,40.0,2352,48.0,B6,97,N592JB,JFK,DEN,265.0,1626,21,23,2013-12-08T02:00:00Z
113633,2013,2,3,2022.0,2055,-33.0,2240.0,2338,-58.0,DL,1715,N612DL,LGA,MSY,162.0,1183,20,55,2013-02-04T01:00:00Z
64501,2013,11,10,1408.0,1440,-32.0,1549.0,1559,-10.0,EV,5713,N825AS,LGA,IAD,52.0,229,14,40,2013-11-10T19:00:00Z
9619,2013,1,11,1900.0,1930,-30.0,2233.0,2243,-10.0,DL,1435,N934DL,LGA,TPA,139.0,1010,19,30,2013-01-12T00:00:00Z
24915,2013,1,29,1703.0,1730,-27.0,1947.0,1957,-10.0,F9,837,N208FR,LGA,DEN,250.0,1620,17,30,2013-01-29T22:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

In [18]:
# Which flights travelled the farthest? Which travelled the shortest?
# Farthest
display(flights.sort_values(by='distance', ascending=False).head(1))
# Shortest
display(flights.sort_values(by='distance', ascending=True).head(1))

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
118311,2013,2,9,1206.0,900,186.0,1814.0,1540,154.0,HA,51,N380HA,JFK,HNL,645.0,4983,9,0,2013-02-09T14:00:00Z

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
275945,2013,7,27,NaN,106,NaN,NaN,245,NaN,US,1632,NaN,EWR,LGA,NaN,17,1,6,2013-07-27T05:00:00Z

## Question 3. Selecting Columns

Use at least three ways to select dep_time, dep_delay, arr_time, and arr_delay from flights.

In [19]:
# Method 1
flights[['dep_time', 'dep_delay', 'arr_time', 'arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [20]:
# Method 2
flights.loc[:, ['dep_time', 'dep_delay', 'arr_time', 'arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [21]:
# Method 3
flights.filter(items=['dep_time', 'dep_delay', 'arr_time', 'arr_delay'])

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

## Question 4. Adding new columns

Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers.

For example, 759 means 7:59 and 801 means 8:01. Their difference is not 42 but 2 minutes.

In [22]:
# Convert them to a more convenient representation of number of minutes since midnight (0).
dep_time_mins = (flights['dep_time'] // 100 * 60 + flights['dep_time'] % 100) % 1440
sched_dep_time_mins = (flights['sched_dep_time'] // 100 * 60 + flights['sched_dep_time'] % 100) % 1440
display(dep_time_mins, sched_dep_time_mins)

0         317.0
1         333.0
2         342.0
3         344.0
4         354.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: dep_time, Length: 336776, dtype: float64

0          315
1          329
2          340
3          345
4          360
          ...
336771     895
336772    1320
336773     730
336774     719
336775     520
Name: sched_dep_time, Length: 336776, dtype: int64

In [23]:
# Create a new column of arr_time - dep_time.
flights['arr_dep_diff'] = flights['arr_time'] - flights['dep_time']

# Compare this column with air_time.
flights[['arr_dep_diff', 'air_time']].head()

   arr_dep_diff  air_time
0         313.0     227.0
1         317.0     227.0
2         381.0     160.0
3         460.0     183.0
4         258.0     116.0

In [24]:
# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# Try creating a column to calculate dep_delay from dep_time and sched_dep_time (and/or other columns if necessary).
dep_time_mins = (flights['dep_time'] // 100 * 60 + flights['dep_time'] % 100)
sched_dep_time_mins = (flights['sched_dep_time'] // 100 * 60 + flights['sched_dep_time'] % 100)
flights['calculated_dep_delay'] = dep_time_mins - sched_dep_time_mins

# Test your results.
flights[['dep_delay', 'calculated_dep_delay']].head()

   dep_delay  calculated_dep_delay
0        2.0                   2.0
1        4.0                   4.0
2        2.0                   2.0
3       -1.0                  -1.0
4       -6.0                  -6.0

## Question 5. Mixing things together

The following questions may require multiple operations above.

In [25]:
# Find the 20 most delayed flights.
# Display the following: year,month,day,carrier,flight,dep_delay,arr_delay,carrier
# How do you want to handle ties?
flights.sort_values('dep_delay', ascending=False).head(20)[['year', 'month', 'day', 'carrier', 'flight', 'dep_delay', 'arr_delay']]

        year  month  day carrier  flight  dep_delay  arr_delay
7072    2013      1    9      HA      51     1301.0     1272.0
235778  2013      6   15      MQ    3535     1137.0     1127.0
8239    2013      1   10      MQ    3695     1126.0     1109.0
327043  2013      9   20      AA     177     1014.0     1007.0
270376  2013      7   22      MQ    3075     1005.0      989.0
173992  2013      4   10      DL    2391      960.0      931.0
151974  2013      3   17      DL    2119      911.0      915.0
247040  2013      6   27      DL    2007      899.0      850.0
270987  2013      7   22      DL    2047      898.0      895.0
87238   2013     12    5      AA     172      896.0      878.0
195711  2013      5    3      MQ    3744      878.0      875.0
151     2013      1    1      MQ    3944      853.0      851.0
210174  2013      5   19      AA     257      853.0      852.0
119784  2013      2   10      F9     835      853.0      834.0
99938   2013     12   19      DL    1223      849.0      847.0
98014   2013     12   17      AA     172      845.0      846.0
95530   2013     12   14      DL    2391      825.0      856.0
182478  2013      4   19      DL    1435      812.0      821.0
246911  2013      6   27      AA    2019      803.0      802.0
152312  2013      3   18      DL    2363      800.0      784.0

In [26]:
# Sort all AA flights to find the top 10 fastest (highest speed) flights.
# Display the following: year,month,day,carrier,flight,orig,dest,distance,air_time,speed (miles per hour)
aa_flights = flights[flights['carrier'] == 'AA'].copy()
aa_flights['speed'] = aa_flights['distance'] / (aa_flights['air_time'] / 60)
aa_flights.sort_values('speed', ascending=False).head(10)[['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'distance', 'air_time', 'speed']]

,year,month,day,carrier,flight,origin,dest,distance,air_time,speed
70704,2013,11,17,AA,936,JFK,STT,1623,175.0,556.457143
87723,2013,12,5,AA,1029,JFK,SJU,1598,173.0,554.219653
119700,2013,2,10,AA,1613,JFK,SJU,1598,173.0,554.219653
129686,2013,2,21,AA,1613,JFK,SJU,1598,174.0,551.034483
87575,2013,12,5,AA,95,JFK,SJU,1598,175.0,547.885714
144408,2013,3,9,AA,1613,JFK,SJU,1598,176.0,544.772727
70721,2013,11,17,AA,1357,JFK,SJU,1598,176.0,544.772727
70335,2013,11,16,AA,95,JFK,SJU,1598,177.0,541.694915
119477,2013,2,10,AA,1635,JFK,SJU,1598,177.0,541.694915
119894,2013,2,11,AA,413,JFK,SJU,1598,177.0,541.694915

In [27]:
# Find all flights that satisfy the following:
# - From John F. Kennedy Airpot (JFK) or Newark Aiport (EWR) to Seattle-Tacoma Airport (SEA)
# - Carrier is UA, AA, or DL.
# - Dates from 4/1/2013 (inclusive) to 4/3/2013 (inclusive)
# - Scheduled arrival time is before noon.
# - Display the following: year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
# - Sort by year, month, day, sched_arr_time

condition = (
    flights['origin'].isin(['JFK', 'EWR']) &
    (flights['dest'] == 'SEA') &
    flights['carrier'].isin(['UA', 'AA', 'DL']) &
    (flights['month'] == 4) &
    flights['day'].between(1, 3) &
    (flights['sched_arr_time'] < 1200)
)

result = flights[condition][['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'sched_dep_time', 'sched_arr_time']]
result.sort_values(['year', 'month', 'day', 'sched_arr_time'])

,year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
165210,2013,4,1,DL,183,JFK,SEA,745,1100
166180,2013,4,2,DL,183,JFK,SEA,745,1100
167168,2013,4,3,DL,183,JFK,SEA,745,1100